/**
 * generate-sitemap.js
 * -------------------
 * Builds the crawler files at BUILD time from one source of truth —
 * `seo.config.json` (the same file vite-plugin-seo.js reads) plus the optional
 * `SITE_URL` env var:
 *     public/sitemap.xml — every public route, so Google/Bing/Ahrefs/
 *                          Screaming Frog/Moz discover the content
 *     public/robots.txt  — Allow: / for public pages, Disallow: for the
 *                          authenticated areas, and the `Sitemap:` pointer
 *
 * Wired into `package.json` as the first step of `build`, so every production
 * deploy publishes files whose URLs point at the real domain (both the Render
 * blueprint and the Dockerfile run `npm run build`):
 *     "build": "node scripts/generate-sitemap.js && vite build"
 *
 * In local `vite dev` the committed `public/sitemap.xml` (production URLs) is
 * served directly — dev is not indexed, so that is fine. If you change domains,
 * set SITE_URL and run `npm run generate-sitemap`.
 *
 * Customisation: add/remove routes in seo.config.json (or extend this script to
 * fetch dynamic routes, e.g. published blog slugs via the API).
 */
require('dotenv').config();
const fs = require('fs');
const path = require('path');

// Shared with vite-plugin-seo.js so canonical/og:url/JSON-LD and the sitemap
// can never drift apart.
const SEO_CONFIG = require('../seo.config.json');

const PUBLIC_DIR = path.join(__dirname, '..', 'public');

// Authenticated / private areas: never listed in the sitemap and explicitly
// disallowed in robots.txt — crawling a login screen only wastes crawl budget.
const DISALLOWED_PREFIXES = ['/admin', '/portal', '/dashboard', '/api/'];

function getSiteUrl() {
  const raw = process.env.SITE_URL || process.env.VITE_SITE_URL || '';
  const fallback = String(SEO_CONFIG.siteUrl || '').trim();
  return (String(raw).trim() || fallback).replace(/\/+$/, '');
}

function publicRoutes() {
  return Array.isArray(SEO_CONFIG.routes) ? SEO_CONFIG.routes : [];
}

// '/' keeps its trailing slash; every other route is appended as-is. An
// absolute value in seo.config.json is used verbatim.
function url(siteUrl, routePath) {
  if (/^https?:\/\//i.test(routePath)) return routePath;
  const suffix = routePath.startsWith('/') ? routePath : '/' + routePath;
  return siteUrl + suffix;
}

function escapeXml(str) {
  return String(str)
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
}

function buildSitemap(siteUrl) {
  const now = new Date().toISOString().slice(0, 10);
  const locs = publicRoutes().map((route) => {
    const loc = url(siteUrl, route.path);
    return [
      '  <url>',
      '    <loc>' + escapeXml(loc) + '</loc>',
      '    <lastmod>' + now + '</lastmod>',
      '    <changefreq>' + escapeXml(route.changefreq || 'monthly') + '</changefreq>',
      '    <priority>' + escapeXml(route.priority || '0.8') + '</priority>',
      '  </url>',
    ].join('\n');
  });
  return [
    '<?xml version="1.0" encoding="UTF-8"?>',
    '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">',
    ...locs,
    '</urlset>',
    '',
  ].join('\n');
}

function buildRobots(siteUrl) {
  const host = siteUrl.replace(/^https?:\/\//, '');
  return [
    '# ==============================================================',
    '# robots.txt — The Greggory Systems And Strategy Firm',
    '# Instructs crawlers (Google, Bing, Ahrefs, Screaming Frog, Moz, etc.)',
    '# on which URLs to index and where to find the sitemap.',
    '# GENERATED by scripts/generate-sitemap.js — edit seo.config.json instead.',
    '# Served from /robots.txt by Express (public/ -> dist/).',
    '# ==============================================================',
    'User-agent: *',
    '# Allow all public pages to be crawled and indexed.',
    '# The private/admin areas below sit behind auth (they return a login page or',
    '# 401) and are deliberately kept out of the sitemap as well.',
    'Allow: /',
    ...DISALLOWED_PREFIXES.map((prefix) => 'Disallow: ' + prefix),
    '',
    '# Sitemap — lists every public route so crawlers discover content.',
    'Sitemap: ' + siteUrl + '/sitemap.xml',
    '',
    '# Host directive (Bing respects this; informs crawlers of the preferred host).',
    'Host: ' + host,
    '',
  ].join('\n');
}

function write(fileName, content) {
  fs.mkdirSync(PUBLIC_DIR, { recursive: true });
  const outPath = path.join(PUBLIC_DIR, fileName);
  fs.writeFileSync(outPath, content, 'utf8');
  console.log('[seo] wrote', outPath);
}

function main() {
  const siteUrl = getSiteUrl();
  if (!siteUrl) {
    console.error('[seo] no site URL — set SITE_URL or seo.config.json "siteUrl"');
    process.exit(1);
  }
  if (!process.env.SITE_URL && !process.env.VITE_SITE_URL) {
    console.log('[seo] SITE_URL not set — falling back to seo.config.json:', siteUrl);
  }
  write('sitemap.xml', buildSitemap(siteUrl));
  write('robots.txt', buildRobots(siteUrl));
  console.log('[seo] ' + publicRoutes().length + ' public URLs, siteUrl=' + siteUrl);
}

main();
